name: CI

permissions:
  contents: read
  packages: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: sandbox-as-a-service/actions/setup-node-with-corepack@v1
